Update update script for GH artifacts (fixes #31)

diff --git a/bin/update b/bin/update
--- a/bin/update
+++ b/bin/update
@@ -1,22 +1,35 @@
 #!/bin/bash
 
-set -eux
+set -eu
 
-cd "$(dirname "${BASH_SOURCE[0]}")/.."
+file="${BASH_SOURCE[0]}"
 
-if [ -z "${CIRCLE_TOKEN:-}" ]; then
+cd "$(dirname "$file")/.."
+
+if [[ $# -eq 0 ]] ; then
+    echo "Usage: $file release_version|circle_build_number.";
+    echo "       $file v0.3.7 or $file 196 (e.g.)";
+    exit 1
+fi
+
+if [[ $1 != v* && -z "${CIRCLE_TOKEN:-}" ]]; then
     echo 'Please set the CIRCLE_TOKEN environment variable. See https://circleci.com/docs/2.0/managing-api-tokens/#creating-a-personal-api-token.';
     exit 1;
 fi
 
-if [[ $# -eq 0 ]] ; then
-    echo "Usage: ${BASH_SOURCE[0]} circle_build_number";
-    exit 1
-fi
+if [[ $1 == v* ]]; then
+    wget "https://github.com/sushain97/web2fs-notepad/releases/download/$1/dist.tar.gz" -O dist.tar.gz
+else
+    artifacts=$(curl -s "https://circleci.com/api/v1.1/project/github/sushain97/web2fs-notepad/$1/artifacts?circle-token=$CIRCLE_TOKEN")
+    dist_url=$(echo "$artifacts" | jq -r '.[] | select(.path=="home/circleci/web2fs-notepad/dist.tar.gz") | .["url"]')
 
-artifacts=$(curl -s "https://circleci.com/api/v1.1/project/github/sushain97/web2fs-notepad/$1/artifacts?circle-token=$CIRCLE_TOKEN")
-dist_url=$(echo "$artifacts" | jq -r '.[] | select(.path=="home/circleci/web2fs-notepad/dist.tar.gz") | .["url"]')
-wget "$dist_url?circle-token=$CIRCLE_TOKEN" -O dist.tar.gz
+    if [[ -z "$dist_url" ]]; then
+        echo "Artifact dist.tar.gz not found for build $1 (found: $artifacts).";
+        exit 1;
+    fi
+
+    wget "$dist_url?circle-token=$CIRCLE_TOKEN" -O dist.tar.gz
+fi
 
 rm -rfv public/assets
 tar -xvf dist.tar.gz
